### ISSUE TITLE
Search results fail when trying to go beyond one page

### ISSUE THREAD

**Issue by cashaffer** [CSSPLICE/splice-catalog#21]
When doing a keyword search, the results are broken into a series of pages. The links to the pages are in the lower left corner as a series of numbers and a Next link. However, clicking on any of these leads to a page with this error:
{"success":false,"message":"Invalid route"}

**Comment by awhicks** [comment]
Current search is not a long term solution, we should consult with Peter about how we should correctly handle search as the collection gets larger (some external library like https://github.com/nextapps-de/flexsearch?)

**Comment by babz007** [comment]
Please check if you are still experiencing any broken pages in the search results. The pagination should now display the rest of the search results correctly. I have also noted the library Alex suggested; perhaps we could bring it up in our next catalog discussion with Peter. Thanks

**Comment by cashaffer** [comment]
Seems to be working now.
